[project]
name = "disjoint-set"
version = "0.9.0"
description = "Disjoint Set data structure implementation for Python"
authors = [{ name = "Maciej Rapacz", email = "mmrapacz@protonmail.ch" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = ["typing-extensions"]

[dependency-groups]
dev = [
    "pytest>=8.1.1,<9",
    "pre-commit==3.5.0",
    "toml>=0.10.2",
    "pyright>=1.1.408",
    "setuptools",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["disjoint_set"]
module-root = ""

[build-system]
requires = ["uv_build>=0.8.24,<0.9.0"]
build-backend = "uv_build"
